import { slugifyTitle } from "@/constants/news";
import {
  formatNewsDisplayDate,
  newsPublishedYear,
} from "@/lib/cms/news-cms";

const UUID_ID_TABLES = new Set(["news", "products"]);

function uniqueSlug(base: string): string {
  const stamp = Date.now().toString(36);
  const slug = slugifyTitle(base) || "untitled";
  return `${slug}-${stamp}`;
}

/** Tables whose primary key is generated by the database (uuid). */
export function collectionUsesGeneratedId(table: string): boolean {
  return UUID_ID_TABLES.has(table);
}

/** Sensible blank row for creating a new CMS collection entry. */
export function getCollectionCreateDefaults(
  table: string
): Record<string, unknown> {
  const year = new Date().getFullYear();

  switch (table) {
    case "news": {
      const title = "Untitled article";
      const createdAt = new Date();
      return {
        slug: uniqueSlug(title),
        category: "Press Release",
        display_date: formatNewsDisplayDate(createdAt),
        published_year: newsPublishedYear(createdAt),
        title,
        image_src: "",
        image_alt: "",
        body_html: "",
        status: "published",
        published_at: createdAt.toISOString(),
      };
    }
    case "careers": {
      const title = "Untitled role";
      const slug = uniqueSlug(title);
      return {
        id: slug,
        slug,
        status: "Open",
        title,
        location: "",
        category: "Corporate Support",
        experience_level: "",
        apply_deadline: "",
        description: "",
        sort_order: 0,
      };
    }
    case "rnd": {
      const title = "Untitled program";
      const id = uniqueSlug(title);
      return {
        id,
        title,
        regimen: "",
        description: "",
        phase: "",
        target_launch: "",
        tags: [],
        featured: false,
        sort_order: 0,
        is_published: false,
      };
    }
    case "products": {
      const title = "Untitled product";
      return {
        slug: uniqueSlug(title),
        title,
        brand: "Selatox",
        eyebrow: "",
        tagline: "",
        short_description: "",
        description: "",
        spec_headline: "",
        spec_eyebrow: "",
        image_src: "",
        image_alt: "",
        category: "Others",
        value_chips: [],
        regulatory_tags: [],
        specs: [],
        sort_order: 0,
        is_published: false,
      };
    }
    case "roadmap": {
      const title = "Untitled milestone";
      return {
        id: uniqueSlug(title),
        year: String(year),
        title,
        section: "milestone",
        status: "upcoming",
        image: "",
        image_bg: null,
        items: [],
        sort_order: 0,
        is_published: false,
      };
    }
    default:
      throw new Error(`Unsupported collection table: ${table}`);
  }
}
